/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppAdminRouteRouteImport } from './routes/_app/admin/route'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppOrganizationRouteImport } from './routes/_app/organization'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation/$invitationId'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminOrganizationsRouteImport } from './routes/_app/admin/organizations'
import { Route as AppAdminSettingsRouteImport } from './routes/_app/admin/settings'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppProjectsNewRouteImport } from './routes/_app/projects/new'
import { Route as ApiArtifactsSplatRouteImport } from './routes/api/artifacts/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiFilesFileIdRouteImport } from './routes/api/files/$fileId'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app/projects/$projectId/index'
import { Route as ApiProjectsProjectIdFilesRouteImport } from './routes/api/projects/$projectId/files'
import { Route as ApiReportsKindIdRouteImport } from './routes/api/reports/$kind/$id'
import { Route as ApiV1ExecutionsExecutionIdRouteImport } from './routes/api/v1/executions/$executionId'
import { Route as ApiV1JobsJobIdRouteImport } from './routes/api/v1/jobs/$jobId'
import { Route as AppProjectsProjectIdIntentsIntentIdRouteImport } from './routes/_app/projects/$projectId/intents/$intentId'
import { Route as AppProjectsProjectIdRunsRunIdRouteImport } from './routes/_app/projects/$projectId/runs/$runId'
import { Route as ApiV1ExecutionsExecutionIdReportRouteImport } from './routes/api/v1/executions/$executionId/report'
import { Route as ApiV1ProjectsProjectIdRunsRouteImport } from './routes/api/v1/projects/$projectId/runs'
import { Route as ApiV1ProjectsProjectIdTestsRouteImport } from './routes/api/v1/projects/$projectId/tests'
import { Route as AppProjectsProjectIdRunsRunIdTraceRouteImport } from './routes/_app/projects/$projectId/runs/$runId_/trace'
import { Route as ApiV1ProjectsProjectIdTestsTestIdGenerateRouteImport } from './routes/api/v1/projects/$projectId/tests/$testId/generate'
import { Route as ApiV1ProjectsProjectIdTestsTestIdRunsRouteImport } from './routes/api/v1/projects/$projectId/tests/$testId/runs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminOrganizationsRoute = AppAdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiArtifactsSplatRoute = ApiArtifactsSplatRouteImport.update({
  id: '/api/artifacts/$',
  path: '/api/artifacts/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesFileIdRoute = ApiFilesFileIdRouteImport.update({
  id: '/api/files/$fileId',
  path: '/api/files/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApiProjectsProjectIdFilesRoute =
  ApiProjectsProjectIdFilesRouteImport.update({
    id: '/api/projects/$projectId/files',
    path: '/api/projects/$projectId/files',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiReportsKindIdRoute = ApiReportsKindIdRouteImport.update({
  id: '/api/reports/$kind/$id',
  path: '/api/reports/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ExecutionsExecutionIdRoute =
  ApiV1ExecutionsExecutionIdRouteImport.update({
    id: '/api/v1/executions/$executionId',
    path: '/api/v1/executions/$executionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1JobsJobIdRoute = ApiV1JobsJobIdRouteImport.update({
  id: '/api/v1/jobs/$jobId',
  path: '/api/v1/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsProjectIdIntentsIntentIdRoute =
  AppProjectsProjectIdIntentsIntentIdRouteImport.update({
    id: '/projects/$projectId/intents/$intentId',
    path: '/projects/$projectId/intents/$intentId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppProjectsProjectIdRunsRunIdRoute =
  AppProjectsProjectIdRunsRunIdRouteImport.update({
    id: '/projects/$projectId/runs/$runId',
    path: '/projects/$projectId/runs/$runId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApiV1ExecutionsExecutionIdReportRoute =
  ApiV1ExecutionsExecutionIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => ApiV1ExecutionsExecutionIdRoute,
  } as any)
const ApiV1ProjectsProjectIdRunsRoute =
  ApiV1ProjectsProjectIdRunsRouteImport.update({
    id: '/api/v1/projects/$projectId/runs',
    path: '/api/v1/projects/$projectId/runs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ProjectsProjectIdTestsRoute =
  ApiV1ProjectsProjectIdTestsRouteImport.update({
    id: '/api/v1/projects/$projectId/tests',
    path: '/api/v1/projects/$projectId/tests',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppProjectsProjectIdRunsRunIdTraceRoute =
  AppProjectsProjectIdRunsRunIdTraceRouteImport.update({
    id: '/projects/$projectId/runs/$runId_/trace',
    path: '/projects/$projectId/runs/$runId/trace',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApiV1ProjectsProjectIdTestsTestIdGenerateRoute =
  ApiV1ProjectsProjectIdTestsTestIdGenerateRouteImport.update({
    id: '/$testId/generate',
    path: '/$testId/generate',
    getParentRoute: () => ApiV1ProjectsProjectIdTestsRoute,
  } as any)
const ApiV1ProjectsProjectIdTestsTestIdRunsRoute =
  ApiV1ProjectsProjectIdTestsTestIdRunsRouteImport.update({
    id: '/$testId/runs',
    path: '/$testId/runs',
    getParentRoute: () => ApiV1ProjectsProjectIdTestsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/organization': typeof AppOrganizationRoute
  '/settings': typeof AppSettingsRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/admin/organizations': typeof AppAdminOrganizationsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/api/artifacts/$': typeof ApiArtifactsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/api/projects/$projectId/files': typeof ApiProjectsProjectIdFilesRoute
  '/api/reports/$kind/$id': typeof ApiReportsKindIdRoute
  '/api/v1/executions/$executionId': typeof ApiV1ExecutionsExecutionIdRouteWithChildren
  '/api/v1/jobs/$jobId': typeof ApiV1JobsJobIdRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/intents/$intentId': typeof AppProjectsProjectIdIntentsIntentIdRoute
  '/projects/$projectId/runs/$runId': typeof AppProjectsProjectIdRunsRunIdRoute
  '/api/v1/executions/$executionId/report': typeof ApiV1ExecutionsExecutionIdReportRoute
  '/api/v1/projects/$projectId/runs': typeof ApiV1ProjectsProjectIdRunsRoute
  '/api/v1/projects/$projectId/tests': typeof ApiV1ProjectsProjectIdTestsRouteWithChildren
  '/projects/$projectId/runs/$runId/trace': typeof AppProjectsProjectIdRunsRunIdTraceRoute
  '/api/v1/projects/$projectId/tests/$testId/generate': typeof ApiV1ProjectsProjectIdTestsTestIdGenerateRoute
  '/api/v1/projects/$projectId/tests/$testId/runs': typeof ApiV1ProjectsProjectIdTestsTestIdRunsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/organization': typeof AppOrganizationRoute
  '/settings': typeof AppSettingsRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/admin/organizations': typeof AppAdminOrganizationsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/api/artifacts/$': typeof ApiArtifactsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/api/projects/$projectId/files': typeof ApiProjectsProjectIdFilesRoute
  '/api/reports/$kind/$id': typeof ApiReportsKindIdRoute
  '/api/v1/executions/$executionId': typeof ApiV1ExecutionsExecutionIdRouteWithChildren
  '/api/v1/jobs/$jobId': typeof ApiV1JobsJobIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/intents/$intentId': typeof AppProjectsProjectIdIntentsIntentIdRoute
  '/projects/$projectId/runs/$runId': typeof AppProjectsProjectIdRunsRunIdRoute
  '/api/v1/executions/$executionId/report': typeof ApiV1ExecutionsExecutionIdReportRoute
  '/api/v1/projects/$projectId/runs': typeof ApiV1ProjectsProjectIdRunsRoute
  '/api/v1/projects/$projectId/tests': typeof ApiV1ProjectsProjectIdTestsRouteWithChildren
  '/projects/$projectId/runs/$runId/trace': typeof AppProjectsProjectIdRunsRunIdTraceRoute
  '/api/v1/projects/$projectId/tests/$testId/generate': typeof ApiV1ProjectsProjectIdTestsTestIdGenerateRoute
  '/api/v1/projects/$projectId/tests/$testId/runs': typeof ApiV1ProjectsProjectIdTestsTestIdRunsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/admin': typeof AppAdminRouteRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/organization': typeof AppOrganizationRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/_app/admin/organizations': typeof AppAdminOrganizationsRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/projects/new': typeof AppProjectsNewRoute
  '/api/artifacts/$': typeof ApiArtifactsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/api/projects/$projectId/files': typeof ApiProjectsProjectIdFilesRoute
  '/api/reports/$kind/$id': typeof ApiReportsKindIdRoute
  '/api/v1/executions/$executionId': typeof ApiV1ExecutionsExecutionIdRouteWithChildren
  '/api/v1/jobs/$jobId': typeof ApiV1JobsJobIdRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/_app/projects/$projectId/intents/$intentId': typeof AppProjectsProjectIdIntentsIntentIdRoute
  '/_app/projects/$projectId/runs/$runId': typeof AppProjectsProjectIdRunsRunIdRoute
  '/api/v1/executions/$executionId/report': typeof ApiV1ExecutionsExecutionIdReportRoute
  '/api/v1/projects/$projectId/runs': typeof ApiV1ProjectsProjectIdRunsRoute
  '/api/v1/projects/$projectId/tests': typeof ApiV1ProjectsProjectIdTestsRouteWithChildren
  '/_app/projects/$projectId/runs/$runId_/trace': typeof AppProjectsProjectIdRunsRunIdTraceRoute
  '/api/v1/projects/$projectId/tests/$testId/generate': typeof ApiV1ProjectsProjectIdTestsTestIdGenerateRoute
  '/api/v1/projects/$projectId/tests/$testId/runs': typeof ApiV1ProjectsProjectIdTestsTestIdRunsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/admin'
    | '/dashboard'
    | '/organization'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/accept-invitation/$invitationId'
    | '/admin/organizations'
    | '/admin/settings'
    | '/projects/new'
    | '/api/artifacts/$'
    | '/api/auth/$'
    | '/api/files/$fileId'
    | '/admin/'
    | '/projects/'
    | '/api/projects/$projectId/files'
    | '/api/reports/$kind/$id'
    | '/api/v1/executions/$executionId'
    | '/api/v1/jobs/$jobId'
    | '/projects/$projectId/'
    | '/projects/$projectId/intents/$intentId'
    | '/projects/$projectId/runs/$runId'
    | '/api/v1/executions/$executionId/report'
    | '/api/v1/projects/$projectId/runs'
    | '/api/v1/projects/$projectId/tests'
    | '/projects/$projectId/runs/$runId/trace'
    | '/api/v1/projects/$projectId/tests/$testId/generate'
    | '/api/v1/projects/$projectId/tests/$testId/runs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/organization'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/accept-invitation/$invitationId'
    | '/admin/organizations'
    | '/admin/settings'
    | '/projects/new'
    | '/api/artifacts/$'
    | '/api/auth/$'
    | '/api/files/$fileId'
    | '/admin'
    | '/projects'
    | '/api/projects/$projectId/files'
    | '/api/reports/$kind/$id'
    | '/api/v1/executions/$executionId'
    | '/api/v1/jobs/$jobId'
    | '/projects/$projectId'
    | '/projects/$projectId/intents/$intentId'
    | '/projects/$projectId/runs/$runId'
    | '/api/v1/executions/$executionId/report'
    | '/api/v1/projects/$projectId/runs'
    | '/api/v1/projects/$projectId/tests'
    | '/projects/$projectId/runs/$runId/trace'
    | '/api/v1/projects/$projectId/tests/$testId/generate'
    | '/api/v1/projects/$projectId/tests/$testId/runs'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/onboarding'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/organization'
    | '/_app/settings'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/accept-invitation/$invitationId'
    | '/_app/admin/organizations'
    | '/_app/admin/settings'
    | '/_app/projects/new'
    | '/api/artifacts/$'
    | '/api/auth/$'
    | '/api/files/$fileId'
    | '/_app/admin/'
    | '/_app/projects/'
    | '/api/projects/$projectId/files'
    | '/api/reports/$kind/$id'
    | '/api/v1/executions/$executionId'
    | '/api/v1/jobs/$jobId'
    | '/_app/projects/$projectId/'
    | '/_app/projects/$projectId/intents/$intentId'
    | '/_app/projects/$projectId/runs/$runId'
    | '/api/v1/executions/$executionId/report'
    | '/api/v1/projects/$projectId/runs'
    | '/api/v1/projects/$projectId/tests'
    | '/_app/projects/$projectId/runs/$runId_/trace'
    | '/api/v1/projects/$projectId/tests/$testId/generate'
    | '/api/v1/projects/$projectId/tests/$testId/runs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  ApiArtifactsSplatRoute: typeof ApiArtifactsSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFilesFileIdRoute: typeof ApiFilesFileIdRoute
  ApiProjectsProjectIdFilesRoute: typeof ApiProjectsProjectIdFilesRoute
  ApiReportsKindIdRoute: typeof ApiReportsKindIdRoute
  ApiV1ExecutionsExecutionIdRoute: typeof ApiV1ExecutionsExecutionIdRouteWithChildren
  ApiV1JobsJobIdRoute: typeof ApiV1JobsJobIdRoute
  ApiV1ProjectsProjectIdRunsRoute: typeof ApiV1ProjectsProjectIdRunsRoute
  ApiV1ProjectsProjectIdTestsRoute: typeof ApiV1ProjectsProjectIdTestsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/organization': {
      id: '/_app/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/organizations': {
      id: '/_app/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AppAdminOrganizationsRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects/new': {
      id: '/_app/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/artifacts/$': {
      id: '/api/artifacts/$'
      path: '/api/artifacts/$'
      fullPath: '/api/artifacts/$'
      preLoaderRoute: typeof ApiArtifactsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$fileId': {
      id: '/api/files/$fileId'
      path: '/api/files/$fileId'
      fullPath: '/api/files/$fileId'
      preLoaderRoute: typeof ApiFilesFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/projects/$projectId/files': {
      id: '/api/projects/$projectId/files'
      path: '/api/projects/$projectId/files'
      fullPath: '/api/projects/$projectId/files'
      preLoaderRoute: typeof ApiProjectsProjectIdFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/$kind/$id': {
      id: '/api/reports/$kind/$id'
      path: '/api/reports/$kind/$id'
      fullPath: '/api/reports/$kind/$id'
      preLoaderRoute: typeof ApiReportsKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/executions/$executionId': {
      id: '/api/v1/executions/$executionId'
      path: '/api/v1/executions/$executionId'
      fullPath: '/api/v1/executions/$executionId'
      preLoaderRoute: typeof ApiV1ExecutionsExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jobs/$jobId': {
      id: '/api/v1/jobs/$jobId'
      path: '/api/v1/jobs/$jobId'
      fullPath: '/api/v1/jobs/$jobId'
      preLoaderRoute: typeof ApiV1JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/$projectId/intents/$intentId': {
      id: '/_app/projects/$projectId/intents/$intentId'
      path: '/projects/$projectId/intents/$intentId'
      fullPath: '/projects/$projectId/intents/$intentId'
      preLoaderRoute: typeof AppProjectsProjectIdIntentsIntentIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects/$projectId/runs/$runId': {
      id: '/_app/projects/$projectId/runs/$runId'
      path: '/projects/$projectId/runs/$runId'
      fullPath: '/projects/$projectId/runs/$runId'
      preLoaderRoute: typeof AppProjectsProjectIdRunsRunIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/v1/executions/$executionId/report': {
      id: '/api/v1/executions/$executionId/report'
      path: '/report'
      fullPath: '/api/v1/executions/$executionId/report'
      preLoaderRoute: typeof ApiV1ExecutionsExecutionIdReportRouteImport
      parentRoute: typeof ApiV1ExecutionsExecutionIdRoute
    }
    '/api/v1/projects/$projectId/runs': {
      id: '/api/v1/projects/$projectId/runs'
      path: '/api/v1/projects/$projectId/runs'
      fullPath: '/api/v1/projects/$projectId/runs'
      preLoaderRoute: typeof ApiV1ProjectsProjectIdRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects/$projectId/tests': {
      id: '/api/v1/projects/$projectId/tests'
      path: '/api/v1/projects/$projectId/tests'
      fullPath: '/api/v1/projects/$projectId/tests'
      preLoaderRoute: typeof ApiV1ProjectsProjectIdTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/$projectId/runs/$runId_/trace': {
      id: '/_app/projects/$projectId/runs/$runId_/trace'
      path: '/projects/$projectId/runs/$runId/trace'
      fullPath: '/projects/$projectId/runs/$runId/trace'
      preLoaderRoute: typeof AppProjectsProjectIdRunsRunIdTraceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/v1/projects/$projectId/tests/$testId/generate': {
      id: '/api/v1/projects/$projectId/tests/$testId/generate'
      path: '/$testId/generate'
      fullPath: '/api/v1/projects/$projectId/tests/$testId/generate'
      preLoaderRoute: typeof ApiV1ProjectsProjectIdTestsTestIdGenerateRouteImport
      parentRoute: typeof ApiV1ProjectsProjectIdTestsRoute
    }
    '/api/v1/projects/$projectId/tests/$testId/runs': {
      id: '/api/v1/projects/$projectId/tests/$testId/runs'
      path: '/$testId/runs'
      fullPath: '/api/v1/projects/$projectId/tests/$testId/runs'
      preLoaderRoute: typeof ApiV1ProjectsProjectIdTestsTestIdRunsRouteImport
      parentRoute: typeof ApiV1ProjectsProjectIdTestsRoute
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminOrganizationsRoute: typeof AppAdminOrganizationsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminOrganizationsRoute: AppAdminOrganizationsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppOrganizationRoute: typeof AppOrganizationRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
  AppProjectsProjectIdIntentsIntentIdRoute: typeof AppProjectsProjectIdIntentsIntentIdRoute
  AppProjectsProjectIdRunsRunIdRoute: typeof AppProjectsProjectIdRunsRunIdRoute
  AppProjectsProjectIdRunsRunIdTraceRoute: typeof AppProjectsProjectIdRunsRunIdTraceRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppOrganizationRoute: AppOrganizationRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  AppProjectsProjectIdIntentsIntentIdRoute:
    AppProjectsProjectIdIntentsIntentIdRoute,
  AppProjectsProjectIdRunsRunIdRoute: AppProjectsProjectIdRunsRunIdRoute,
  AppProjectsProjectIdRunsRunIdTraceRoute:
    AppProjectsProjectIdRunsRunIdTraceRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ApiV1ExecutionsExecutionIdRouteChildren {
  ApiV1ExecutionsExecutionIdReportRoute: typeof ApiV1ExecutionsExecutionIdReportRoute
}

const ApiV1ExecutionsExecutionIdRouteChildren: ApiV1ExecutionsExecutionIdRouteChildren =
  {
    ApiV1ExecutionsExecutionIdReportRoute:
      ApiV1ExecutionsExecutionIdReportRoute,
  }

const ApiV1ExecutionsExecutionIdRouteWithChildren =
  ApiV1ExecutionsExecutionIdRoute._addFileChildren(
    ApiV1ExecutionsExecutionIdRouteChildren,
  )

interface ApiV1ProjectsProjectIdTestsRouteChildren {
  ApiV1ProjectsProjectIdTestsTestIdGenerateRoute: typeof ApiV1ProjectsProjectIdTestsTestIdGenerateRoute
  ApiV1ProjectsProjectIdTestsTestIdRunsRoute: typeof ApiV1ProjectsProjectIdTestsTestIdRunsRoute
}

const ApiV1ProjectsProjectIdTestsRouteChildren: ApiV1ProjectsProjectIdTestsRouteChildren =
  {
    ApiV1ProjectsProjectIdTestsTestIdGenerateRoute:
      ApiV1ProjectsProjectIdTestsTestIdGenerateRoute,
    ApiV1ProjectsProjectIdTestsTestIdRunsRoute:
      ApiV1ProjectsProjectIdTestsTestIdRunsRoute,
  }

const ApiV1ProjectsProjectIdTestsRouteWithChildren =
  ApiV1ProjectsProjectIdTestsRoute._addFileChildren(
    ApiV1ProjectsProjectIdTestsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  ApiArtifactsSplatRoute: ApiArtifactsSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFilesFileIdRoute: ApiFilesFileIdRoute,
  ApiProjectsProjectIdFilesRoute: ApiProjectsProjectIdFilesRoute,
  ApiReportsKindIdRoute: ApiReportsKindIdRoute,
  ApiV1ExecutionsExecutionIdRoute: ApiV1ExecutionsExecutionIdRouteWithChildren,
  ApiV1JobsJobIdRoute: ApiV1JobsJobIdRoute,
  ApiV1ProjectsProjectIdRunsRoute: ApiV1ProjectsProjectIdRunsRoute,
  ApiV1ProjectsProjectIdTestsRoute:
    ApiV1ProjectsProjectIdTestsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
