/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppOrganizationRouteImport } from './routes/_app.organization'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AuthSigninRouteImport } from './routes/_auth.signin'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppAdminOrganizationsRouteImport } from './routes/_app.admin.organizations'
import { Route as AppAdminSettingsRouteImport } from './routes/_app.admin.settings'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppProjectsNewRouteImport } from './routes/_app.projects.new'
import { Route as ApiArtifactsSplatRouteImport } from './routes/api/artifacts.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app.projects.$projectId.index'
import { Route as ApiReportsKindIdRouteImport } from './routes/api/reports.$kind.$id'
import { Route as ApiV1ExecutionsExecutionIdRouteImport } from './routes/api.v1.executions.$executionId'
import { Route as AppProjectsProjectIdIntentsIntentIdRouteImport } from './routes/_app.projects.$projectId.intents.$intentId'
import { Route as AppProjectsProjectIdRunsRunIdRouteImport } from './routes/_app.projects.$projectId.runs.$runId'
import { Route as ApiV1ExecutionsExecutionIdReportRouteImport } from './routes/api.v1.executions.$executionId.report'
import { Route as ApiV1ProjectsProjectIdRunsRouteImport } from './routes/api.v1.projects.$projectId.runs'
import { Route as AppProjectsProjectIdRunsRunIdTraceRouteImport } from './routes/_app.projects.$projectId.runs.$runId_.trace'
import { Route as ApiV1ProjectsProjectIdTestsTestIdRunsRouteImport } from './routes/api.v1.projects.$projectId.tests.$testId.runs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminOrganizationsRoute = AppAdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRoute,
} as any)
const ApiArtifactsSplatRoute = ApiArtifactsSplatRouteImport.update({
  id: '/api/artifacts/$',
  path: '/api/artifacts/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AppRoute,
  } as any)
const ApiReportsKindIdRoute = ApiReportsKindIdRouteImport.update({
  id: '/api/reports/$kind/$id',
  path: '/api/reports/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ExecutionsExecutionIdRoute =
  ApiV1ExecutionsExecutionIdRouteImport.update({
    id: '/api/v1/executions/$executionId',
    path: '/api/v1/executions/$executionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppProjectsProjectIdIntentsIntentIdRoute =
  AppProjectsProjectIdIntentsIntentIdRouteImport.update({
    id: '/projects/$projectId/intents/$intentId',
    path: '/projects/$projectId/intents/$intentId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdRunsRunIdRoute =
  AppProjectsProjectIdRunsRunIdRouteImport.update({
    id: '/projects/$projectId/runs/$runId',
    path: '/projects/$projectId/runs/$runId',
    getParentRoute: () => AppRoute,
  } as any)
const ApiV1ExecutionsExecutionIdReportRoute =
  ApiV1ExecutionsExecutionIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => ApiV1ExecutionsExecutionIdRoute,
  } as any)
const ApiV1ProjectsProjectIdRunsRoute =
  ApiV1ProjectsProjectIdRunsRouteImport.update({
    id: '/api/v1/projects/$projectId/runs',
    path: '/api/v1/projects/$projectId/runs',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppProjectsProjectIdRunsRunIdTraceRoute =
  AppProjectsProjectIdRunsRunIdTraceRouteImport.update({
    id: '/projects/$projectId/runs/$runId_/trace',
    path: '/projects/$projectId/runs/$runId/trace',
    getParentRoute: () => AppRoute,
  } as any)
const ApiV1ProjectsProjectIdTestsTestIdRunsRoute =
  ApiV1ProjectsProjectIdTestsTestIdRunsRouteImport.update({
    id: '/api/v1/projects/$projectId/tests/$testId/runs',
    path: '/api/v1/projects/$projectId/tests/$testId/runs',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/organization': typeof AppOrganizationRoute
  '/settings': typeof AppSettingsRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/admin/organizations': typeof AppAdminOrganizationsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/api/artifacts/$': typeof ApiArtifactsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AppAdminIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/api/reports/$kind/$id': typeof ApiReportsKindIdRoute
  '/api/v1/executions/$executionId': typeof ApiV1ExecutionsExecutionIdRouteWithChildren
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/intents/$intentId': typeof AppProjectsProjectIdIntentsIntentIdRoute
  '/projects/$projectId/runs/$runId': typeof AppProjectsProjectIdRunsRunIdRoute
  '/api/v1/executions/$executionId/report': typeof ApiV1ExecutionsExecutionIdReportRoute
  '/api/v1/projects/$projectId/runs': typeof ApiV1ProjectsProjectIdRunsRoute
  '/projects/$projectId/runs/$runId/trace': typeof AppProjectsProjectIdRunsRunIdTraceRoute
  '/api/v1/projects/$projectId/tests/$testId/runs': typeof ApiV1ProjectsProjectIdTestsTestIdRunsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/organization': typeof AppOrganizationRoute
  '/settings': typeof AppSettingsRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/admin/organizations': typeof AppAdminOrganizationsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/api/artifacts/$': typeof ApiArtifactsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AppAdminIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/api/reports/$kind/$id': typeof ApiReportsKindIdRoute
  '/api/v1/executions/$executionId': typeof ApiV1ExecutionsExecutionIdRouteWithChildren
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/intents/$intentId': typeof AppProjectsProjectIdIntentsIntentIdRoute
  '/projects/$projectId/runs/$runId': typeof AppProjectsProjectIdRunsRunIdRoute
  '/api/v1/executions/$executionId/report': typeof ApiV1ExecutionsExecutionIdReportRoute
  '/api/v1/projects/$projectId/runs': typeof ApiV1ProjectsProjectIdRunsRoute
  '/projects/$projectId/runs/$runId/trace': typeof AppProjectsProjectIdRunsRunIdTraceRoute
  '/api/v1/projects/$projectId/tests/$testId/runs': typeof ApiV1ProjectsProjectIdTestsTestIdRunsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/organization': typeof AppOrganizationRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/_app/admin/organizations': typeof AppAdminOrganizationsRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/projects/new': typeof AppProjectsNewRoute
  '/api/artifacts/$': typeof ApiArtifactsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/api/reports/$kind/$id': typeof ApiReportsKindIdRoute
  '/api/v1/executions/$executionId': typeof ApiV1ExecutionsExecutionIdRouteWithChildren
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/_app/projects/$projectId/intents/$intentId': typeof AppProjectsProjectIdIntentsIntentIdRoute
  '/_app/projects/$projectId/runs/$runId': typeof AppProjectsProjectIdRunsRunIdRoute
  '/api/v1/executions/$executionId/report': typeof ApiV1ExecutionsExecutionIdReportRoute
  '/api/v1/projects/$projectId/runs': typeof ApiV1ProjectsProjectIdRunsRoute
  '/_app/projects/$projectId/runs/$runId_/trace': typeof AppProjectsProjectIdRunsRunIdTraceRoute
  '/api/v1/projects/$projectId/tests/$testId/runs': typeof ApiV1ProjectsProjectIdTestsTestIdRunsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/admin'
    | '/dashboard'
    | '/organization'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/accept-invitation/$invitationId'
    | '/admin/organizations'
    | '/admin/settings'
    | '/projects/new'
    | '/api/artifacts/$'
    | '/api/auth/$'
    | '/admin/'
    | '/projects/'
    | '/api/reports/$kind/$id'
    | '/api/v1/executions/$executionId'
    | '/projects/$projectId/'
    | '/projects/$projectId/intents/$intentId'
    | '/projects/$projectId/runs/$runId'
    | '/api/v1/executions/$executionId/report'
    | '/api/v1/projects/$projectId/runs'
    | '/projects/$projectId/runs/$runId/trace'
    | '/api/v1/projects/$projectId/tests/$testId/runs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/organization'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/accept-invitation/$invitationId'
    | '/admin/organizations'
    | '/admin/settings'
    | '/projects/new'
    | '/api/artifacts/$'
    | '/api/auth/$'
    | '/admin'
    | '/projects'
    | '/api/reports/$kind/$id'
    | '/api/v1/executions/$executionId'
    | '/projects/$projectId'
    | '/projects/$projectId/intents/$intentId'
    | '/projects/$projectId/runs/$runId'
    | '/api/v1/executions/$executionId/report'
    | '/api/v1/projects/$projectId/runs'
    | '/projects/$projectId/runs/$runId/trace'
    | '/api/v1/projects/$projectId/tests/$testId/runs'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/onboarding'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/organization'
    | '/_app/settings'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/accept-invitation/$invitationId'
    | '/_app/admin/organizations'
    | '/_app/admin/settings'
    | '/_app/projects/new'
    | '/api/artifacts/$'
    | '/api/auth/$'
    | '/_app/admin/'
    | '/_app/projects/'
    | '/api/reports/$kind/$id'
    | '/api/v1/executions/$executionId'
    | '/_app/projects/$projectId/'
    | '/_app/projects/$projectId/intents/$intentId'
    | '/_app/projects/$projectId/runs/$runId'
    | '/api/v1/executions/$executionId/report'
    | '/api/v1/projects/$projectId/runs'
    | '/_app/projects/$projectId/runs/$runId_/trace'
    | '/api/v1/projects/$projectId/tests/$testId/runs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  ApiArtifactsSplatRoute: typeof ApiArtifactsSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiReportsKindIdRoute: typeof ApiReportsKindIdRoute
  ApiV1ExecutionsExecutionIdRoute: typeof ApiV1ExecutionsExecutionIdRouteWithChildren
  ApiV1ProjectsProjectIdRunsRoute: typeof ApiV1ProjectsProjectIdRunsRoute
  ApiV1ProjectsProjectIdTestsTestIdRunsRoute: typeof ApiV1ProjectsProjectIdTestsTestIdRunsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization': {
      id: '/_app/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/organizations': {
      id: '/_app/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AppAdminOrganizationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/new': {
      id: '/_app/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/artifacts/$': {
      id: '/api/artifacts/$'
      path: '/api/artifacts/$'
      fullPath: '/api/artifacts/$'
      preLoaderRoute: typeof ApiArtifactsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/reports/$kind/$id': {
      id: '/api/reports/$kind/$id'
      path: '/api/reports/$kind/$id'
      fullPath: '/api/reports/$kind/$id'
      preLoaderRoute: typeof ApiReportsKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/executions/$executionId': {
      id: '/api/v1/executions/$executionId'
      path: '/api/v1/executions/$executionId'
      fullPath: '/api/v1/executions/$executionId'
      preLoaderRoute: typeof ApiV1ExecutionsExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/$projectId/intents/$intentId': {
      id: '/_app/projects/$projectId/intents/$intentId'
      path: '/projects/$projectId/intents/$intentId'
      fullPath: '/projects/$projectId/intents/$intentId'
      preLoaderRoute: typeof AppProjectsProjectIdIntentsIntentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/runs/$runId': {
      id: '/_app/projects/$projectId/runs/$runId'
      path: '/projects/$projectId/runs/$runId'
      fullPath: '/projects/$projectId/runs/$runId'
      preLoaderRoute: typeof AppProjectsProjectIdRunsRunIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/v1/executions/$executionId/report': {
      id: '/api/v1/executions/$executionId/report'
      path: '/report'
      fullPath: '/api/v1/executions/$executionId/report'
      preLoaderRoute: typeof ApiV1ExecutionsExecutionIdReportRouteImport
      parentRoute: typeof ApiV1ExecutionsExecutionIdRoute
    }
    '/api/v1/projects/$projectId/runs': {
      id: '/api/v1/projects/$projectId/runs'
      path: '/api/v1/projects/$projectId/runs'
      fullPath: '/api/v1/projects/$projectId/runs'
      preLoaderRoute: typeof ApiV1ProjectsProjectIdRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/$projectId/runs/$runId_/trace': {
      id: '/_app/projects/$projectId/runs/$runId_/trace'
      path: '/projects/$projectId/runs/$runId/trace'
      fullPath: '/projects/$projectId/runs/$runId/trace'
      preLoaderRoute: typeof AppProjectsProjectIdRunsRunIdTraceRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/v1/projects/$projectId/tests/$testId/runs': {
      id: '/api/v1/projects/$projectId/tests/$testId/runs'
      path: '/api/v1/projects/$projectId/tests/$testId/runs'
      fullPath: '/api/v1/projects/$projectId/tests/$testId/runs'
      preLoaderRoute: typeof ApiV1ProjectsProjectIdTestsTestIdRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminOrganizationsRoute: typeof AppAdminOrganizationsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminOrganizationsRoute: AppAdminOrganizationsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppOrganizationRoute: typeof AppOrganizationRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
  AppProjectsProjectIdIntentsIntentIdRoute: typeof AppProjectsProjectIdIntentsIntentIdRoute
  AppProjectsProjectIdRunsRunIdRoute: typeof AppProjectsProjectIdRunsRunIdRoute
  AppProjectsProjectIdRunsRunIdTraceRoute: typeof AppProjectsProjectIdRunsRunIdTraceRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppOrganizationRoute: AppOrganizationRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  AppProjectsProjectIdIntentsIntentIdRoute:
    AppProjectsProjectIdIntentsIntentIdRoute,
  AppProjectsProjectIdRunsRunIdRoute: AppProjectsProjectIdRunsRunIdRoute,
  AppProjectsProjectIdRunsRunIdTraceRoute:
    AppProjectsProjectIdRunsRunIdTraceRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ApiV1ExecutionsExecutionIdRouteChildren {
  ApiV1ExecutionsExecutionIdReportRoute: typeof ApiV1ExecutionsExecutionIdReportRoute
}

const ApiV1ExecutionsExecutionIdRouteChildren: ApiV1ExecutionsExecutionIdRouteChildren =
  {
    ApiV1ExecutionsExecutionIdReportRoute:
      ApiV1ExecutionsExecutionIdReportRoute,
  }

const ApiV1ExecutionsExecutionIdRouteWithChildren =
  ApiV1ExecutionsExecutionIdRoute._addFileChildren(
    ApiV1ExecutionsExecutionIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  ApiArtifactsSplatRoute: ApiArtifactsSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiReportsKindIdRoute: ApiReportsKindIdRoute,
  ApiV1ExecutionsExecutionIdRoute: ApiV1ExecutionsExecutionIdRouteWithChildren,
  ApiV1ProjectsProjectIdRunsRoute: ApiV1ProjectsProjectIdRunsRoute,
  ApiV1ProjectsProjectIdTestsTestIdRunsRoute:
    ApiV1ProjectsProjectIdTestsTestIdRunsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
