/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppOrganizationRouteImport } from './routes/_app.organization'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AuthSigninRouteImport } from './routes/_auth.signin'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppAdminOrganizationsRouteImport } from './routes/_app.admin.organizations'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as ApiArtifactsSplatRouteImport } from './routes/api/artifacts.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiSpikeBrowserRouteImport } from './routes/api/spike/browser'
import { Route as ApiSpikeWorkflowStatusRouteImport } from './routes/api/spike/workflow-status'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app.projects.$projectId.index'
import { Route as ApiSpikeLoaderIndexRouteImport } from './routes/api/spike/loader/index'
import { Route as AppProjectsProjectIdIntentsIntentIdRouteImport } from './routes/_app.projects.$projectId.intents.$intentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminOrganizationsRoute = AppAdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const ApiArtifactsSplatRoute = ApiArtifactsSplatRouteImport.update({
  id: '/api/artifacts/$',
  path: '/api/artifacts/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpikeBrowserRoute = ApiSpikeBrowserRouteImport.update({
  id: '/api/spike/browser',
  path: '/api/spike/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpikeWorkflowStatusRoute = ApiSpikeWorkflowStatusRouteImport.update({
  id: '/api/spike/workflow-status',
  path: '/api/spike/workflow-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AppRoute,
  } as any)
const ApiSpikeLoaderIndexRoute = ApiSpikeLoaderIndexRouteImport.update({
  id: '/api/spike/loader/',
  path: '/api/spike/loader/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsProjectIdIntentsIntentIdRoute =
  AppProjectsProjectIdIntentsIntentIdRouteImport.update({
    id: '/projects/$projectId/intents/$intentId',
    path: '/projects/$projectId/intents/$intentId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/organization': typeof AppOrganizationRoute
  '/settings': typeof AppSettingsRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/admin/organizations': typeof AppAdminOrganizationsRoute
  '/api/artifacts/$': typeof ApiArtifactsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/spike/browser': typeof ApiSpikeBrowserRoute
  '/api/spike/workflow-status': typeof ApiSpikeWorkflowStatusRoute
  '/admin/': typeof AppAdminIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/api/spike/loader/': typeof ApiSpikeLoaderIndexRoute
  '/projects/$projectId/intents/$intentId': typeof AppProjectsProjectIdIntentsIntentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/organization': typeof AppOrganizationRoute
  '/settings': typeof AppSettingsRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/admin/organizations': typeof AppAdminOrganizationsRoute
  '/api/artifacts/$': typeof ApiArtifactsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/spike/browser': typeof ApiSpikeBrowserRoute
  '/api/spike/workflow-status': typeof ApiSpikeWorkflowStatusRoute
  '/admin': typeof AppAdminIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/api/spike/loader': typeof ApiSpikeLoaderIndexRoute
  '/projects/$projectId/intents/$intentId': typeof AppProjectsProjectIdIntentsIntentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/organization': typeof AppOrganizationRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/_app/admin/organizations': typeof AppAdminOrganizationsRoute
  '/api/artifacts/$': typeof ApiArtifactsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/spike/browser': typeof ApiSpikeBrowserRoute
  '/api/spike/workflow-status': typeof ApiSpikeWorkflowStatusRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/api/spike/loader/': typeof ApiSpikeLoaderIndexRoute
  '/_app/projects/$projectId/intents/$intentId': typeof AppProjectsProjectIdIntentsIntentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/admin'
    | '/dashboard'
    | '/organization'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/accept-invitation/$invitationId'
    | '/admin/organizations'
    | '/api/artifacts/$'
    | '/api/auth/$'
    | '/api/spike/browser'
    | '/api/spike/workflow-status'
    | '/admin/'
    | '/projects/'
    | '/projects/$projectId/'
    | '/api/spike/loader/'
    | '/projects/$projectId/intents/$intentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/organization'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/accept-invitation/$invitationId'
    | '/admin/organizations'
    | '/api/artifacts/$'
    | '/api/auth/$'
    | '/api/spike/browser'
    | '/api/spike/workflow-status'
    | '/admin'
    | '/projects'
    | '/projects/$projectId'
    | '/api/spike/loader'
    | '/projects/$projectId/intents/$intentId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/onboarding'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/organization'
    | '/_app/settings'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/accept-invitation/$invitationId'
    | '/_app/admin/organizations'
    | '/api/artifacts/$'
    | '/api/auth/$'
    | '/api/spike/browser'
    | '/api/spike/workflow-status'
    | '/_app/admin/'
    | '/_app/projects/'
    | '/_app/projects/$projectId/'
    | '/api/spike/loader/'
    | '/_app/projects/$projectId/intents/$intentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  ApiArtifactsSplatRoute: typeof ApiArtifactsSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSpikeBrowserRoute: typeof ApiSpikeBrowserRoute
  ApiSpikeWorkflowStatusRoute: typeof ApiSpikeWorkflowStatusRoute
  ApiSpikeLoaderIndexRoute: typeof ApiSpikeLoaderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization': {
      id: '/_app/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/organizations': {
      id: '/_app/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AppAdminOrganizationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/artifacts/$': {
      id: '/api/artifacts/$'
      path: '/api/artifacts/$'
      fullPath: '/api/artifacts/$'
      preLoaderRoute: typeof ApiArtifactsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spike/browser': {
      id: '/api/spike/browser'
      path: '/api/spike/browser'
      fullPath: '/api/spike/browser'
      preLoaderRoute: typeof ApiSpikeBrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spike/workflow-status': {
      id: '/api/spike/workflow-status'
      path: '/api/spike/workflow-status'
      fullPath: '/api/spike/workflow-status'
      preLoaderRoute: typeof ApiSpikeWorkflowStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/spike/loader/': {
      id: '/api/spike/loader/'
      path: '/api/spike/loader'
      fullPath: '/api/spike/loader/'
      preLoaderRoute: typeof ApiSpikeLoaderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/$projectId/intents/$intentId': {
      id: '/_app/projects/$projectId/intents/$intentId'
      path: '/projects/$projectId/intents/$intentId'
      fullPath: '/projects/$projectId/intents/$intentId'
      preLoaderRoute: typeof AppProjectsProjectIdIntentsIntentIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminOrganizationsRoute: typeof AppAdminOrganizationsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminOrganizationsRoute: AppAdminOrganizationsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppOrganizationRoute: typeof AppOrganizationRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
  AppProjectsProjectIdIntentsIntentIdRoute: typeof AppProjectsProjectIdIntentsIntentIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppOrganizationRoute: AppOrganizationRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  AppProjectsProjectIdIntentsIntentIdRoute:
    AppProjectsProjectIdIntentsIntentIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  ApiArtifactsSplatRoute: ApiArtifactsSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSpikeBrowserRoute: ApiSpikeBrowserRoute,
  ApiSpikeWorkflowStatusRoute: ApiSpikeWorkflowStatusRoute,
  ApiSpikeLoaderIndexRoute: ApiSpikeLoaderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
